name: Build and Deploy

on:
  [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run the build command
        run: npm run build

      - name: Move services to dist
        run: |
          cp services/contact-us.html dist/contact-us
          cp services/sendmail.php dist/sendmail.php

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST_KEY: ${{ secrets.SSH_HOST_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Add server's SSH key to known_hosts to avoid host verification prompt
          echo "$SSH_HOST_KEY" >> ~/.ssh/known_hosts

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy to server
        env:
          RSYNC_TARGET: ${{ secrets.RSYNC_TARGET }}
        run: rsync -avz --delete dist/ $RSYNC_TARGET
